/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projetoredes;

import java.util.Arrays;
import javax.swing.JOptionPane;

/**
 *
 * @author Osni Cena
 */
public class FrmLogin extends javax.swing.JFrame {
    telaPrincipal   mainScreen = new telaPrincipal();
      private boolean checkPassword (char[] password){
        boolean check = true;
         char [] correctPassword = {'f','a','t','e','c'}; // Array de char contendo senha correta
         
         if(password.length != correctPassword.length){ //Verifica se o tamanho da senha digitada pelo usuário é diferente da senha correta
             check = false;
         }else{
             check = Arrays.equals(correctPassword,password); //Arrays.equals compara valores de 2 arrays, retorna true para igual e false para diferente
         }
       
         
         
          Arrays.fill(correctPassword,'0'); //Preenche a variavel com 0 por razões de segurança     
          
          
          return check; //Retorna true para senha correta ou falso para senha incorreta
       }
    
    
    /**
     * Creates new form FrmLogin
     */
    public FrmLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPassword = new javax.swing.JPasswordField();
        jLabelPassword = new javax.swing.JLabel();
        jButtonLogin = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Security Area");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("Security Area");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, 430, 50));

        jPassword.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        getContentPane().add(jPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 180, 290, 30));

        jLabelPassword.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabelPassword.setText("Password:");
        getContentPane().add(jLabelPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, 170, 30));

        jButtonLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/padlock_closed.png"))); // NOI18N
        jButtonLogin.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jButtonLoginMouseMoved(evt);
            }
        });
        jButtonLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonLoginMouseExited(evt);
            }
        });
        jButtonLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLoginActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 260, 100, 50));

        jLabel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 600, 250));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLoginActionPerformed
      char[] password = jPassword.getPassword();
        
        boolean ok;
        
        if (checkPassword(password) == true){
            mainScreen.setVisible(true);
            this.dispose();
        }else{
            JOptionPane.showMessageDialog(null, "Invalid password. ","Error",JOptionPane.ERROR_MESSAGE);
        }
     
      Arrays.fill(password, '0'); // Preenche password com 0 por razões de segurança
    }//GEN-LAST:event_jButtonLoginActionPerformed

    private void jButtonLoginMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonLoginMouseMoved
       jButtonLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/padlock_open.png")));
    }//GEN-LAST:event_jButtonLoginMouseMoved

    private void jButtonLoginMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonLoginMouseExited
       jButtonLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/padlock_closed.png")));
    }//GEN-LAST:event_jButtonLoginMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmLogin().setVisible(true);
        }
            });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelPassword;
    private javax.swing.JPasswordField jPassword;
    // End of variables declaration//GEN-END:variables
}
